### ISSUE TITLE
How to check self hosted runner per OS?

### ISSUE THREAD

**Issue by rvbc1** [BenjaminMichaelis/get-soonest-available-runner#1]
Great add-on—thanks for your work on it! However, I’ve encountered an issue when checking runner availability per OS. I build the same application for two systems (macOS and Linux), but it appears that if my macOS runner is available, the add-on returns a positive result for both macOS and Linux. As a result, I end up with two self-hosted assignments (for macOS and Linux) and two fallbacks, even though I would expect the availability check to be evaluated separately per OS.

Here’s my current workflow configuration:
```
jobs:
  prepare-matrix:
    name: Prepare Dynamic Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Get best runner for Linux
        id: linux-runner
        uses: benjaminmichaelis/get-soonest-available-runner@v1.1.0
        with:
          primary-runner: "self-hosted"
          fallback-runner: "ubuntu-latest"
          min-available-runners: 2
          github-token: ${{ secrets.GHTOKEN_DETERMINERUNNER }}

      - name: Get best runner for macOS
        id: macos-runner
        uses: benjaminmichaelis/get-soonest-available-runner@v1.1.0
        with:
          primary-runner: "self-hosted"
          fallback-runner: "macos-latest"
          min-available-runners: 2
          github-token: ${{ secrets.GHTOKEN_DETERMINERUNNER }}

      - name: Set matrix
        id: set-matrix
        shell: bash
        run: |
          linux_runner="${{ steps.linux-runner.outputs.runner }}"
          macos_runner="${{ steps.macos-runner.outputs.runner }}"
          matrix=$(cat <<EOF
          {
            "include": [
              { "os": "Linux", "runner": "$linux_runner" },
              { "os": "macOS", "runner": "$macos_runner" }
            ]
          }
          EOF
          )
              echo "matrix<<EOF" >> $GITHUB_OUTPUT
              echo "$matrix" >> $GITHUB_OUTPUT
              echo "EOF" >> $GITHUB_OUTPUT
```

In the scenario where only my macOS runner is available, the check for Linux incorrectly returns true (using the self-hosted runner) instead of falling back to “ubuntu-latest.” Is there any way to perform the runner availability check per operating system so that each OS’s assignment can be handled independently?

Any help or suggestions would be greatly appreciated!

Thank you in advance!

**Comment by BenjaminMichaelis** [comment]
Instead of self-hosted which looks for anything in the pool of your self-hosted runners (albeit mac, linux, etc). Can you put another label on them like "self-hosted-linux" or similar so it checks just that pool?

ex:
```yaml
 - name: Get best runner for Linux
        id: linux-runner
        uses: benjaminmichaelis/get-soonest-available-runner@v1.1.0
        with:
          primary-runner: "self-hosted-linux"
          fallback-runner: "ubuntu-latest"
          min-available-runners: 2
          github-token: ${{ secrets.GHTOKEN_DETERMINERUNNER }}

      - name: Get best runner for macOS
        id: macos-runner
        uses: benjaminmichaelis/get-soonest-available-runner@v1.1.0
        with:
          primary-runner: "self-hosted-mac"
          fallback-runner: "macos-latest"
          min-available-runners: 2
          github-token: ${{ secrets.GHTOKEN_DETERMINERUNNER }}
```
